### PR TITLE
Did some cleaning up and made it more cross platform.

### PR DESCRIPTION
**Pull request by TheLandfill**
I also dealt with some constants. I'm just trying to get the base set up and I'll probably do everything else by tomorrow. I mostly made it cross platform using macros. If you define WINDOWS in your project settings, you'll be right back where you were. I also slowed down the frame rate.

Lastly, I removed the executable.

### CODE REVIEW

**Comment by TheLandfill** [comment]
I would also like to point out that you use a lot of non-const global variables. While it's not a big deal here, it could easily become a big deal later when writing larger and larger projects.

**Comment by ferrara44** [comment]
https://imgur.com/a/3Hazwuy

Some terminal sequences are not being interpreted. Might it be my editor/compiler?

**Comment by TheLandfill** [comment]
It's your terminal. You should probably do some "#ifdef" stuff to avoid using them for Windows programs.

I think there's also some Windows functions that can make the terminal emulate a VT terminal.

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

The terminal codes I've added clear the screen on my Linux terminal, but I don't know how Windows works with it. On my side, it works without crashing, but I don't know how it's doing with respect to the Game of Life.

**Comment by ferrara44** [comment]
I'll go for the #ifdef route I guess. Something I'll have to learn eventually. Better now than never.

This does not solve the issue that it's currently not following the rules of the game.

> Any live cell with fewer than two live neighbours dies.
    Any live cell with more than three live neighbours dies.
    Any live cell with two or three live neighbours lives, unchanged, to the next generation.
    Any dead cell with exactly three live neighbours will come to life.

We'll rebase and merge this once it's working, right?

**Comment by TheLandfill** [comment]
Of course. I'll see if I can't fix the rule implementation, while you might want to try to get the Windows side working. Essentially, we just need to tell Windows to handle the escape sequences.

Let's see if I can get the rules to be as simple as possible. A cell will be alive in the next generation if it has exactly three neighbors (regardless of whether it is alive) or it is alive and it has two neighbors, correct?

**Comment by ferrara44** [comment]
•barren cells become alive if (neighbors=3).
•living cells become barren if (neighbors>3 || neighbors<2) .

Those are the rules that change the state of the current cell being evaluated. Otherwise the cell remains unchanged (4+ neighbors don't make a barren cell alive).

**Comment by ferrara44** [comment]
The current state of this branch is still not following the rules of the game, you can cross check it with the main branch and see how the behavior is different, easier noticed with small groups in a step by step basis.

**Comment by ferrara44** [comment]
Honestly I don't know if I'm too sleepy or unexperienced, but I don't get the logic of the evaluate function. I couldn't get what rules is is actually folowing.
Some empty spaces with 4 neighbours become alive and some other overcrowded spaces keep their 'o' value without dying. But I couldn't get what rules are being followed nor understand your code.

**Comment by TheLandfill** [comment]
I apologize for my mistake. Each cell has eight neighbors (excluding edge cells) which form a 3x3 block around them. I go through each element of the 3x3 block, which includes the current cell in the center of the block. The code I should have had would have skipped over the current cell in the center. The code I did have skipped over the entire diagonal of the 3x3 block from the top left to the top right.

I also added an explanation of the method. I should have been more clear to start out. Basically, the rules state that a cell is alive in the next iteration if any of the following are true

- it was alive in the last iteration and it has two or three neighbors
- it was dead in the last iteration and it has three neighbors

otherwise, it's dead. These rules are equivalent to saying that a cell is alive in the next iteration if

- it has three neighbors
- it has two neighbors and is alive

which is what I test for since it has fewer variables.

Once again, I apologize for my error.

**Review by ferrara44 — APPROVED** [review]

**Pull request merged**
